import { jsPDF } from "jspdf";

/**
 * Generates an ATS-compliant resume PDF from Claude's optimization output
 * 
 * FIXED VERSION - Simplified to avoid parsing crashes
 */

export function generateAtsResumePdf(claudeOutput, candidateName = "Your Name") {
  try {
    const doc = new jsPDF();
    
    // Page settings
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - (margin * 2);
    let yPosition = margin;
    
    // ──────────────────────────────────────────────────────────────────────
    // HEADER
    // ──────────────────────────────────────────────────────────────────────
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(candidateName.toUpperCase(), pageWidth / 2, yPosition, { align: "center" });
    yPosition += 8;
    
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text("Email: your.email@example.com | Phone: +353 XX XXX XXXX | LinkedIn: linkedin.com/in/yourprofile", pageWidth / 2, yPosition, { align: "center" });
    yPosition += 12;
    
    // ──────────────────────────────────────────────────────────────────────
    // CONTENT - Just output the Claude text directly with basic formatting
    // ──────────────────────────────────────────────────────────────────────
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    
    // Split content into lines and add page breaks
    const lines = doc.splitTextToSize(claudeOutput, contentWidth);
    
    lines.forEach((line) => {
      // Check if we need a new page
      if (yPosition > pageHeight - 20) {
        doc.addPage();
        yPosition = margin;
      }
      
      doc.text(line, margin, yPosition);
      yPosition += 5;
    });
    
    // ──────────────────────────────────────────────────────────────────────
    // FOOTER
    // ──────────────────────────────────────────────────────────────────────
    if (yPosition > pageHeight - 25) {
      doc.addPage();
      yPosition = margin;
    }
    
    yPosition += 10;
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.text("Generated by ApplyIQ | ATS-Optimized Resume", margin, yPosition);
    
    // ──────────────────────────────────────────────────────────────────────
    // SAVE
    // ──────────────────────────────────────────────────────────────────────
    const filename = `Resume_ATS_Optimized_${new Date().toISOString().slice(0, 10)}.pdf`;
    doc.save(filename);
    
    console.log("PDF generated successfully!");
    return true;
    
  } catch (error) {
    console.error("PDF generation failed:", error);
    throw new Error(`Failed to generate PDF: ${error.message}`);
  }
}